steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/crace:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crace:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crace'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crace:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '100'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,COINMARKETCAP_API_KEY=${_COINMARKETCAP_API_KEY}'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/crace:$COMMIT_SHA'

# Substitution variables
substitutions:
  _COINMARKETCAP_API_KEY: 'your-coinmarketcap-api-key-here'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
